# potrebno je stvoriti env.yml file u kojem ce biti sadrzani DB_NAME, DB_USERNAME i DB_PASSWORD u sljedecem obliku:
# DB_NAME: your_database_name
# DB_USERNAME: your_database_username
# DB_PASSWORD: your_database_password

spring:
  application:
    name: Musclemind
  config:
    import: file:env.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #format_sql: true
        #show_sql: true
    database: postgresql
