# potrebno je stvoriti env.yml file u kojem ce biti sadrzani DB_NAME, DB_USERNAME i DB_PASSWORD u sljedecem obliku:
# DB_NAME: your_database_name
# DB_USERNAME: your_database_username
# DB_PASSWORD: your_database_password

spring:
  application:
    name: Musclemind
  config:
    import: file:env.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:./database/uloga_insert.sql, classpath:./database/tezina_insert.sql, classpath:./database/vidljivost_insert.sql, classpath:./database/kategorija_insert.sql, classpath:./database/vjezba_insert.sql
