/*uloga*/
DELETE FROM uloga;
INSERT INTO uloga (naziv_uloga) VALUES
    ('ROLE_ADMIN'),
    ('ROLE_USER');
/*tezina*/
DELETE FROM tezina;
INSERT INTO tezina (naziv_tezina) VALUES
    ('Lagano'),
    ('Srednje'),
    ('Teško'),
    ('Vrlo teško');
/*vidljivost*/
DELETE FROM vidljivost;
INSERT INTO vidljivost (naziv_vidljivost) VALUES
    ('Javno'),
    ('Privatno');
/*kategorija*/
DELETE FROM kategorija;
INSERT INTO kategorija (naziv_kategorija, slika) VALUES
   ('Prsa', '../assets/categoris/Prsa.png'),
   ('Triceps', '../assets/categoris/Triceps.png'),
   ('Prsa-Triceps', '../assets/categoris/Prsa-Triceps.png'),
   ('Leđa', '../assets/categoris/Leđa.png'),
   ('Biceps', '../assets/categoris/Biceps.png'),
   ('Leđa-Biceps', '../assets/categoris/Leđa-Biceps.png'),
   ('Ramena', '../assets/categoris/Ramena.png'),
   ('Abdomen', '../assets/categoris/Abdomen.png'),
   ('Kvadriceps', '../assets/categoris/Kvadriceps.png'),
   ('Zadnja loža', '../assets/categoris/Zadnja loža.png'),
   ('Kvadriceps-Zadnja loža', '../assets/categoris/Kvadriceps-Zadnja loža.png'),
   ('Listovi', '../assets/categoris/Listovi.png');
/*vjezba*/
DELETE FROM vjezba;
INSERT INTO vjezba (naziv_vjezba, id_kategorija) VALUES
    ('Razvlačenja s bučicama', 1),
    ('Razvlačenja s bučicama pod nagibom', 1),
    ('Letenja povlačenjem sajle', 1),
    ('Jednoručna letenja povlačenjem sajle', 1),
    ('Pulloveri s bučicama', 1),
    ('Pulloveri s pločnim utegom', 1),
    ('Pulloveri s girjom', 1),
    ('Pulloveri s EZ šipkom', 1),
    ('Ekstenzije pomoću sajle', 2),
    ('Ekstenzije pomoću sajle iznad glave', 2),
    ('Ekstenzije na ravnoj šipci', 2),
    ('Ekstenzije na karikama', 2),
    ('Ležeće ekstenzije s bučicama', 2),
    ('Ležeće ekstenzije s EZ šipkom', 2),
    ('Sjedeće ekstenzije iznad glave s bučicama', 2),
    ('Sjedeće ekstenzije iznad glave s EZ šipkom', 2),
    ('Propadanja na klupi', 2),
    ('Uska propadanja na klupi', 2),
    ('Sklekovi', 3),
    ('Sklekovi s opterećenjem', 3),
    ('Široki sklekovi', 3),
    ('Široki sklekovi s opterećenjem', 3),
    ('Dijamantski sklekovi', 3),
    ('Dijamantski sklekovi s opterećenjem', 3),
    ('Sklekovi na karikama', 3),
    ('Sklekovi na karikama s opterećenjem', 3),
    ('Propadanja', 3),
    ('Propadanja s opterećenjem', 3),
    ('Propadanja na ravnoj šipci', 3),
    ('Propadanja na karikama', 3),
    ('Propadanja na karikama s opterećenjem', 3),
    ('Potisak sa šipkom', 3),
    ('Potisak sa šipkom pod nagibom', 3),
    ('Potisak sa šipkom s uskim hvatom', 3),
    ('Potisak sa šipkom s uskim hvatom pod nagibom', 3),
    ('Potisak sa šipkom sa širokim hvatom', 3),
    ('Potisak sa šipkom sa širokim hvatom pod nagibom', 3),
    ('Potisci s bučicama na klupi', 3),
    ('Potisci s bučicama pod nagibom', 3),
    ('Mrtva dizanja', 4),
    ('Sumo mrtva dizanja', 4),
    ('Povlačanja lat mašine sa širokim hvatom', 4),
    ('Veslanja u pretklonu sa šipkom', 4),
    ('Slijeganja ramenima s bučicama', 4),
    ('Jednoručna veslanja s bučicama', 4),
    ('Hiperekstenzije', 4),
    ('Veslanja s T šipkom stojeći', 4),
    ('Veslanja na spravi', 4),
    ('Veslanja na spravi jednom rukom', 4),
    ('Veslanja na spravi sa širokim hvatom', 4),
    ('Okomita veslanja', 4),
    ('Zgibovi sa širokim hvatom', 4),
    ('Zgibovi sa širokim hvatom s opterećenjem', 4),
    ('Stojeći pregibi sa šipkom', 5),
    ('Stojeći pregibi s bučicama', 5),
    ('Čekić pregibi s bučicama', 5),
    ('Pregibi na Scottovoj klupi', 5),
    ('Pregibi na klupi s nagibom', 5),
    ('Koncentracijski pregibi s bučicom', 5),
    ('Uvijanje ruku na karikama', 5),
    ('Zgibovi', 6),
    ('Zgibovi s opterećenjem', 6),
    ('Zgibovi s uskim hvatom', 6),
    ('Zgibovi s uskim hvatom s opterećenjem', 6),
    ('Zgibovi s neutralnim hvatom', 6),
    ('Zgibovi s neutralnim hvatom s opterećenjem', 6),
    ('Zgibovi s obrnutim hvatom', 6),
    ('Zgibovi s obrnutim hvatom s opterećenjem', 6),
    ('Veslanja na spravi s uskim hvatom', 6),
    ('Povlačenja lat mašine', 6),
    ('Povlačenja lat mašine s uskom hvatom', 6),
    ('Povlačenja lat mašine s obrnutim hvatom', 6),
    ('Australski zgibovi', 6),
    ('Australski zgibovi s opterećenjem', 6),
    ('Stojeći potisci sa šipkom', 7),
    ('Sjedeći potisci s bučicama', 7),
    ('Frontalna podizanja bučicama', 7),
    ('Bočna podizanja bučicama', 7),
    ('Bočna povlačenja sajle', 7),
    ('Odručenja u pretklonu', 7),
    ('Povlačenja sajle prema licu', 7),
    ('Trbušnjaci', 8),
    ('Trbušnjaci s podignutim nogama', 8),
    ('Trbušnjaci s laktovima do koljena', 8),
    ('Biciklistički trbušnjaci', 8),
    ('Plank', 8),
    ('Plank sa skokovima', 8),
    ('Plank u bočnom položaju', 8),
    ('Ruski okreti', 8),
    ('Naizmjenična podizanja nogu u ležećem položaju', 8),
    ('Podizanja nogu u visećem položaju', 8),
    ('Obrnuti trbušnjaci', 8),
    ('V-sit trbušnjaci', 8),
    ('Trbušnjaci na spravi', 8),
    ('Trbušnjaci sa sajlom', 8),
    ('Nožne ekstenzije na mašini', 9),
    ('Sissy čučnjevi', 9),
    ('Čučnjevi s uskim stavom', 9),
    ('Čučnjevi s uskim stavom s opterećenjem', 9),
    ('Rumunjska mrtva dizanje', 10),
    ('Nožne fleksije na mašini', 10),
    ('Nožne fleksije pomoću sajle', 10),
    ('Good mornings', 10),
    ('Glute-ham podizanja', 10),
    ('Čučnjevi', 11),
    ('Čučnjevi sa stražnjim opterećenjem', 11),
    ('Čučnjevi sa prednjim opterećenjem', 11),
    ('Čučnjevi na Smith mašini', 11),
    ('Goblet čučnjevi', 11),
    ('Box čučnjevi', 11),
    ('Nožna preša', 11),
    ('Iskoraci', 11),
    ('Iskoraci s opterećenjem', 11),
    ('Bugarski čučnjevi', 11),
    ('Bugarski čučnjevi s opterećenjem', 11),
    ('Stražnji dijagonalni iskorak', 11),
    ('Stojeće plantarne fleksije stopala', 12),
    ('Stojeće plantarne fleksije stopala s opterećenjem', 12),
    ('Jednonožne stojeće plantarne fleksije stopala', 12),
    ('Jednonožne stojeće plantarne fleskije stopala s opterećenjem', 12),
    ('Plantarne fleksije stopala u pretklonu', 12),
    ('Plantarne fleksije stopala na nožnoj preši', 12),
    ('Sjedeće plantarne fleksije stopala na mašini', 12),
    ('Sjedeće plantarne fleksije stopala s bugarskom vrećom', 12),
    ('Sjedeće plantarne fleksije stopala s utegom', 12);
