INSERT INTO vjezba (id_vjezba, naziv_vjezba, id_kategorija) VALUES
                                                     (nextVal('vjezba_seq'), 'Razvlačenja s bučicama', 1),
                                                     (nextVal('vjezba_seq'), 'Razvlačenja s bučicama pod nagibom', 1),
                                                     (nextVal('vjezba_seq'), 'Letenja povlačenjem sajle', 1),
                                                     (nextVal('vjezba_seq'), 'Jednoručna letenja povlačenjem sajle', 1),
                                                     (nextVal('vjezba_seq'), 'Pulloveri s bučicama', 1),
                                                     (nextVal('vjezba_seq'), 'Pulloveri s pločnim utegom', 1),
                                                     (nextVal('vjezba_seq'), 'Pulloveri s girjom', 1),
                                                     (nextVal('vjezba_seq'), 'Pulloveri s EZ šipkom', 1),
                                                     (nextVal('vjezba_seq'), 'Ekstenzije pomoću sajle', 2),
                                                     (nextVal('vjezba_seq'), 'Ekstenzije pomoću sajle iznad glave', 2),
                                                     (nextVal('vjezba_seq'), 'Ekstenzije na ravnoj šipci', 2),
                                                     (nextVal('vjezba_seq'), 'Ekstenzije na karikama', 2),
                                                     (nextVal('vjezba_seq'), 'Ležeće ekstenzije s bučicama', 2),
                                                     (nextVal('vjezba_seq'), 'Ležeće ekstenzije s EZ šipkom', 2),
                                                     (nextVal('vjezba_seq'), 'Sjedeće ekstenzije iznad glave s bučicama', 2),
                                                     (nextVal('vjezba_seq'), 'Sjedeće ekstenzije iznad glave s EZ šipkom', 2),
                                                     (nextVal('vjezba_seq'), 'Propadanja na klupi', 2),
                                                     (nextVal('vjezba_seq'), 'Uska propadanja na klupi', 2),
                                                     (nextVal('vjezba_seq'), 'Sklekovi', 3),
                                                     (nextVal('vjezba_seq'), 'Sklekovi s opterećenjem', 3),
                                                     (nextVal('vjezba_seq'), 'Široki sklekovi', 3),
                                                     (nextVal('vjezba_seq'), 'Široki sklekovi s opterećenjem', 3),
                                                     (nextVal('vjezba_seq'), 'Dijamantski sklekovi', 3),
                                                     (nextVal('vjezba_seq'), 'Dijamantski sklekovi s opterećenjem', 3),
                                                     (nextVal('vjezba_seq'), 'Sklekovi na karikama', 3),
                                                     (nextVal('vjezba_seq'), 'Sklekovi na karikama s opterećenjem', 3),
                                                     (nextVal('vjezba_seq'), 'Propadanja', 3),
                                                     (nextVal('vjezba_seq'), 'Propadanja s opterećenjem', 3),
                                                     (nextVal('vjezba_seq'), 'Propadanja na ravnoj šipci', 3),
                                                     (nextVal('vjezba_seq'), 'Propadanja na karikama', 3),
                                                     (nextVal('vjezba_seq'), 'Propadanja na karikama s opterećenjem', 3),
                                                     (nextVal('vjezba_seq'), 'Potisak sa šipkom', 3),
                                                     (nextVal('vjezba_seq'), 'Potisak sa šipkom pod nagibom', 3),
                                                     (nextVal('vjezba_seq'), 'Potisak sa šipkom s uskim hvatom', 3),
                                                     (nextVal('vjezba_seq'), 'Potisak sa šipkom s uskim hvatom pod nagibom', 3),
                                                     (nextVal('vjezba_seq'), 'Potisak sa šipkom sa širokim hvatom', 3),
                                                     (nextVal('vjezba_seq'), 'Potisak sa šipkom sa širokim hvatom pod nagibom', 3),
                                                     (nextVal('vjezba_seq'), 'Potisci s bučicama na klupi', 3),
                                                     (nextVal('vjezba_seq'), 'Potisci s bučicama pod nagibom', 3),
                                                     (nextVal('vjezba_seq'), 'Mrtva dizanja', 4),
                                                     (nextVal('vjezba_seq'), 'Sumo mrtva dizanja', 4),
                                                     (nextVal('vjezba_seq'), 'Povlačanja lat mašine sa širokim hvatom', 4),
                                                     (nextVal('vjezba_seq'), 'Veslanja u pretklonu sa šipkom', 4),
                                                     (nextVal('vjezba_seq'), 'Slijeganja ramenima s bučicama', 4),
                                                     (nextVal('vjezba_seq'), 'Jednoručna veslanja s bučicama', 4),
                                                     (nextVal('vjezba_seq'), 'Hiperekstenzije', 4),
                                                     (nextVal('vjezba_seq'), 'Veslanja s T šipkom stojeći', 4),
                                                     (nextVal('vjezba_seq'), 'Veslanja na spravi', 4),
                                                     (nextVal('vjezba_seq'), 'Veslanja na spravi jednom rukom', 4),
                                                     (nextVal('vjezba_seq'), 'Veslanja na spravi sa širokim hvatom', 4),
                                                     (nextVal('vjezba_seq'), 'Okomita veslanja', 4),
                                                     (nextVal('vjezba_seq'), 'Zgibovi sa širokim hvatom', 4),
                                                     (nextVal('vjezba_seq'), 'Zgibovi sa širokim hvatom s opterećenjem', 4),
                                                     (nextVal('vjezba_seq'), 'Stojeći pregibi sa šipkom', 5),
                                                     (nextVal('vjezba_seq'), 'Stojeći pregibi s bučicama', 5),
                                                     (nextVal('vjezba_seq'), 'Čekić pregibi s bučicama', 5),
                                                     (nextVal('vjezba_seq'), 'Pregibi na Scottovoj klupi', 5),
                                                     (nextVal('vjezba_seq'), 'Pregibi na klupi s nagibom', 5),
                                                     (nextVal('vjezba_seq'), 'Koncentracijski pregibi s bučicom', 5),
                                                     (nextVal('vjezba_seq'), 'Uvijanje ruku na karikama', 5),
                                                     (nextVal('vjezba_seq'), 'Zgibovi', 6),
                                                     (nextVal('vjezba_seq'), 'Zgibovi s opterećenjem', 6),
                                                     (nextVal('vjezba_seq'), 'Zgibovi s uskim hvatom', 6),
                                                     (nextVal('vjezba_seq'), 'Zgibovi s uskim hvatom s opterećenjem', 6),
                                                     (nextVal('vjezba_seq'), 'Zgibovi s neutralnim hvatom', 6),
                                                     (nextVal('vjezba_seq'), 'Zgibovi s neutralnim hvatom s opterećenjem', 6),
                                                     (nextVal('vjezba_seq'), 'Zgibovi s obrnutim hvatom', 6),
                                                     (nextVal('vjezba_seq'), 'Zgibovi s obrnutim hvatom s opterećenjem', 6),
                                                     (nextVal('vjezba_seq'), 'Veslanja na spravi s uskim hvatom', 6),
                                                     (nextVal('vjezba_seq'), 'Povlačenja lat mašine', 6),
                                                     (nextVal('vjezba_seq'), 'Povlačenja lat mašine s uskom hvatom', 6),
                                                     (nextVal('vjezba_seq'), 'Povlačenja lat mašine s obrnutim hvatom', 6),
                                                     (nextVal('vjezba_seq'), 'Australski zgibovi', 6),
                                                     (nextVal('vjezba_seq'), 'Australski zgibovi s opterećenjem', 6),
                                                     (nextVal('vjezba_seq'), 'Stojeći potisci sa šipkom', 7),
                                                     (nextVal('vjezba_seq'), 'Sjedeći potisci s bučicama', 7),
                                                     (nextVal('vjezba_seq'), 'Frontalna podizanja bučicama', 7),
                                                     (nextVal('vjezba_seq'), 'Bočna podizanja bučicama', 7),
                                                     (nextVal('vjezba_seq'), 'Bočna povlačenja sajle', 7),
                                                     (nextVal('vjezba_seq'), 'Odručenja u pretklonu', 7),
                                                     (nextVal('vjezba_seq'), 'Povlačenja sajle prema licu', 7),
                                                     (nextVal('vjezba_seq'), 'Trbušnjaci', 8),
                                                     (nextVal('vjezba_seq'), 'Trbušnjaci s podignutim nogama', 8),
                                                     (nextVal('vjezba_seq'), 'Trbušnjaci s laktovima do koljena', 8),
                                                     (nextVal('vjezba_seq'), 'Biciklistički trbušnjaci', 8),
                                                     (nextVal('vjezba_seq'), 'Plank', 8),
                                                     (nextVal('vjezba_seq'), 'Plank sa skokovima', 8),
                                                     (nextVal('vjezba_seq'), 'Plank u bočnom položaju', 8),
                                                     (nextVal('vjezba_seq'), 'Ruski okreti', 8),
                                                     (nextVal('vjezba_seq'), 'Naizmjenična podizanja nogu u ležećem položaju', 8),
                                                     (nextVal('vjezba_seq'), 'Podizanja nogu u visećem položaju', 8),
                                                     (nextVal('vjezba_seq'), 'Obrnuti trbušnjaci', 8),
                                                     (nextVal('vjezba_seq'), 'V-sit trbušnjaci', 8),
                                                     (nextVal('vjezba_seq'), 'Trbušnjaci na spravi', 8),
                                                     (nextVal('vjezba_seq'), 'Trbušnjaci sa sajlom', 8),
                                                     (nextVal('vjezba_seq'), 'Nožne ekstenzije na mašini', 9),
                                                     (nextVal('vjezba_seq'), 'Sissy čučnjevi', 9),
                                                     (nextVal('vjezba_seq'), 'Čučnjevi s uskim stavom', 9),
                                                     (nextVal('vjezba_seq'), 'Čučnjevi s uskim stavom s opterećenjem', 9),
                                                     (nextVal('vjezba_seq'), 'Rumunjska mrtva dizanje', 10),
                                                     (nextVal('vjezba_seq'), 'Nožne fleksije na mašini', 10),
                                                     (nextVal('vjezba_seq'), 'Nožne fleksije pomoću sajle', 10),
                                                     (nextVal('vjezba_seq'), 'Good mornings', 10),
                                                     (nextVal('vjezba_seq'), 'Glute-ham podizanja', 10),
                                                     (nextVal('vjezba_seq'), 'Čučnjevi', 11),
                                                     (nextVal('vjezba_seq'), 'Čučnjevi sa stražnjim opterećenjem', 11),
                                                     (nextVal('vjezba_seq'), 'Čučnjevi sa prednjim opterećenjem', 11),
                                                     (nextVal('vjezba_seq'), 'Čučnjevi na Smith mašini', 11),
                                                     (nextVal('vjezba_seq'), 'Goblet čučnjevi', 11),
                                                     (nextVal('vjezba_seq'), 'Box čučnjevi', 11),
                                                     (nextVal('vjezba_seq'), 'Nožna preša', 11),
                                                     (nextVal('vjezba_seq'), 'Iskoraci', 11),
                                                     (nextVal('vjezba_seq'), 'Iskoraci s opterećenjem', 11),
                                                     (nextVal('vjezba_seq'), 'Bugarski čučnjevi', 11),
                                                     (nextVal('vjezba_seq'), 'Bugarski čučnjevi s opterećenjem', 11),
                                                     (nextVal('vjezba_seq'), 'Stražnji dijagonalni iskorak', 11),
                                                     (nextVal('vjezba_seq'), 'Stojeće plantarne fleksije stopala', 12),
                                                     (nextVal('vjezba_seq'), 'Stojeće plantarne fleksije stopala s opterećenjem', 12),
                                                     (nextVal('vjezba_seq'), 'Jednonožne stojeće plantarne fleksije stopala', 12),
                                                     (nextVal('vjezba_seq'), 'Jednonožne stojeće plantarne fleskije stopala s opterećenjem', 12),
                                                     (nextVal('vjezba_seq'), 'Plantarne fleksije stopala u pretklonu', 12),
                                                     (nextVal('vjezba_seq'), 'Plantarne fleksije stopala na nožnoj preši', 12),
                                                     (nextVal('vjezba_seq'), 'Sjedeće plantarne fleksije stopala na mašini', 12),
                                                     (nextVal('vjezba_seq'), 'Sjedeće plantarne fleksije stopala s bugarskom vrećom', 12),
                                                     (nextVal('vjezba_seq'), 'Sjedeće plantarne fleksije stopala s utegom', 12) ON CONFLICT DO NOTHING;
